### PR TITLE
Page title

### PR DESCRIPTION
**Pull request by aliusa**
Added page title, but needs refactor, because it's height cut off.
Also title doesn't wrap when reached screen margins.

### CODE REVIEW

**Comment by aliusa** [comment]
screenshot_1

I managed to get it working with bottom indicator, because it adjusts height.

screenshot_3

This is how text being cut off.

**Comment by badoualy** [comment]
Can you add more space between the indicator and the text please? This is way too close

**Comment by aliusa** [comment]
Okay, added stylable property of margin and tried to seperate from bottom indicator, but somewhy text is being cut off. Could you please improve my code?

screenshot_3

**Comment by badoualy** [comment]
Need to update 
https://github.com/badoualy/stepper-indicator/blob/master/library/src/main/java/com/badoualy/stepperindicator/StepperIndicator.java#L877

to add additional height when displaying text

**Comment by aliusa** [comment]
Yeah, I tried to add label height, but maybe couldn't calculate.
https://github.com/badoualy/stepper-indicator/pull/21/commits/fade7b18dc4bdc9612f459c69a858a4db6d86a10#diff-73af2c6ac03587cfc7a06da40bc781f1R928

**Comment by rakshakhegde** [comment]
Hey, I very badly needed this Label support. So I've made the required changes to the repo. Please review my PR here: #31

**Comment by badoualy** [comment]
Closed in favor of #31

**Pull request closed without merging**
