### PR TITLE
Added support for steps click event

### PR DESCRIPTION
**Pull request by IonutNegru87**
Custom Gesture Detector - to detect click/tap events
Custom steps click areas method - setup the exact click areas for each step
Utility methods for adding/removing/clearing listeners for click events - multiple listeners are supported
JavDoc for added methods, fields and classes - for better understanding the functionality

### CODE REVIEW

**Comment by badoualy** [comment]
Good for me, just a small question, why use a `GestureDetector` instead of just storing the coordinates of event in `onTouch` then just override `onClick` method in the view?

Ps: We could test if listener list is empty in the gesture before testing each areas, no need to do it if we don't have a listener anyway :)

**Comment by IonutNegru87** [comment]
I chose to use GestureDetector as it is easier to correctly detect click events, and we don't need the onClick even set for the view. You can use that for an general click event for the entire view in the future if you want.

I agree with the optimization for the listener verification, it is better to do before  :)

**Comment by badoualy** [comment]
Good for me then

**Comment by IonutNegru87** [comment]
I've made the changes for the optimizations regarding the click events listeners.

**Comment by IonutNegru87** [comment]
Seems I committed them after you merged, I will make a new pull request for it. 
Thank you for the suggestion :D

**Comment by badoualy** [comment]
Thanks!
I renamed some fields, personally I'm not a fan of the "m" prefix before fields name, so I changed that :laughing:

**Pull request merged**
