### PR TITLE
Support for extra customizations

### PR DESCRIPTION
**Pull request by IonutNegru87**
Hello,

I've added support for:

Step text number label
Multiple colors support for each step
Bottom line indicator (best used in combination with text number)
Multiple colors support for bottom line indicator

Here is an usage example:

```
<com.badoualy.stepperindicator.StepperIndicator
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:layout_marginTop="10dp"
      app:stpi_circleColor="@color/light_gray"
      app:stpi_circleRadius="10dp"
      app:stpi_circleStrokeWidth="2dp"
      app:stpi_lineColor="@color/light_gray"
      app:stpi_lineDoneColor="@color/blue"
      app:stpi_showStepNumberInstead="true"
      app:stpi_stepCount="4"
      app:stpi_stepsCircleColors="@array/stpi_steps_colors"
      app:stpi_stepsIndicatorColors="@array/stpi_steps_colors"
      app:stpi_useBottomIndicator="true"
      app:stpi_useBottomIndicatorWithStepColors="true"
      />
```

If there is something wrong with the implementation or if you have recommendations for optimizations let me know.

The only thing I've not added support for (and I've wanted, but I do not have that much time to do it these day) is for the the bottom indicator animation. If you have an quick idea on how to do it, please do it :D...

Thank you and have a good day :D

### CODE REVIEW

**Comment by IonutNegru87** [comment]
Here is the doc table describing each attribute:

```
<table><thead>
<tr>
<th>Name</th>
<th>Description</th>
<th>Default value</th>
</tr>
</thead><tbody>
<tr>
<td>stpi_animDuration</td>
<td>duration of the line tracing animation</td>
<td>250 ms</td>
</tr>
<tr>
<td>stpi_stepCount</td>
<td>number of pages/steps</td>
<td></td>
</tr>
<tr>
<td>stpi_circleColor</td>
<td>color of the stroke circle</td>
<td>#b3bdc2 (grey)</td>
</tr>
<tr>
<td>stpi_circleRadius</td>
<td>radius of the circle</td>
<td>10dp</td>
</tr>
<tr>
<td>stpi_circleStrokeWidth</td>
<td>width of circle's radius</td>
<td>4dp</td>
</tr>
<tr>
<td>stpi_indicatorColor</td>
<td>color for the current page indicator</td>
<td>#00b47c (green)</td>
</tr>
<tr>
<td>stpi_indicatorRadius</td>
<td>radius for the circle of the current page indicator</td>
<td>4dp</td>
</tr>
<tr>
<td>stpi_lineColor</td>
<td>color of the line between indicators</td>
<td>#b3bdc2 (grey)</td>
</tr>
<tr>
<td>stpi_lineDoneColor</td>
<td>color of a line when step is done</td>
<td>#00b47c (green)</td>
</tr>
<tr>
<td>stpi_lineStrokeWidth</td>
<td>width of the line stroke</td>
<td>2dp</td>
</tr>
<tr>
<td>stpi_lineMargin</td>
<td>margin at each side of the line</td>
<td>5dp</td>
</tr>
<tr>
<td>stpi_showDoneIcon</td>
<td>show the done check icon or not</td>
<td>true</td>
</tr>
<tr>
<td>stpi_showStepNumberInstead</td>
<td>display text number for each step instead of bullets</td>
<td>false</td>
</tr>
<tr>
<td>stpi_useBottomIndicator</td>
<td>display the indicator for the current step at the bottom instead of inside bullet</td>
<td>false</td>
</tr>
 <tr>
<td>stpi_useBottomIndicatorWithStepColors</td>
<td>use the same color for the bottom indicator as the step color</td>
<td>false</td>
</tr>
<tr>
<td>stpi_bottomIndicatorHeight</td>
<td>set the height for the bottom indicator component</td>
<td>3dp</td>
</tr>
<tr>
<td>stpi_bottomIndicatorWidth</td>
<td>set the width for the bottom indicator component</td>
<td>50dp</td>
</tr>
<tr>
<td>stpi_bottomIndicatorMarginTop</td>
<td>set the top margin for the bottom indicator component</td>
<td>10dp</td>
</tr>
<tr>
<td>stpi_stepsCircleColors</td>
<td>use multiple colors for each step (array of colors with the size at least the same size as the stpi_stepCount value)</td>
<td></td>
</tr>
<tr>
<td>stpi_stepsIndicatorColors</td>
<td>use multiple colors for each step indicator (array of colors with the size at least the same size as the stpi_stepCount value)</td>
<td></td>
</tr>
</tbody></table>
```

You can use it to update the readme file of the library when you want.

**Comment by IonutNegru87** [comment]
There is an issue with how the bottom indicator is drawn,  I'll try and fix it asap and I'll make a new commit.

**Comment by IonutNegru87** [comment]
Hello,
I've made the fix. Have a look at it when you have time.

**Comment by aliusa** [comment]
I opened issue #16, where I suggest to show page title below step circle.
I see you added **Step text number label**, is there possibility to add page title?

**Comment by IonutNegru87** [comment]
Hello @aliusa,

Yes it can be done. And it doesn't need that many changes. The idea is that the position of the text is calculated dynamically once the step is initialized:

This is the logic for computing the position of the text number:

```
final String stepLabel = String.valueOf(i + 1);

Rect stepAreaRect = new Rect((int) (indicator - mCircleRadius), (int) (centerY - mCircleRadius),
                             (int) (indicator + mCircleRadius), (int) (centerY + mCircleRadius));
RectF stepBounds = new RectF(stepAreaRect);

Paint stepTextNumberPaint = getStepTextNumberPaint(i);

// measure text width
stepBounds.right = stepTextNumberPaint.measureText(stepLabel, 0, stepLabel.length());
// measure text height
stepBounds.bottom = stepTextNumberPaint.descent() - stepTextNumberPaint.ascent();

stepBounds.left += (stepAreaRect.width() - stepBounds.right) / 2.0f;
stepBounds.top += (stepAreaRect.height() - stepBounds.bottom) / 2.0f;
```

If you want to put the text right under the step indicator, you should update these. I also recommend to do this with some attributes so that the developer can choose which style to use. The step label can also be updated to accept custom title namings.

**Comment by badoualy** [comment]
I'll try to merge now, but as I said in previous commit, I'm not a fan of the "m" prefix before fields name, so I'll have to rename all of them, plus it's complicating the change diff :cry:

**Comment by aliusa** [comment]
Well, there's [Java coding convention, which Android project follows](https://source.android.com/source/code-style.html#follow-field-naming-conventions) which strictly rules to use _m_, bet either way, here, it's not enforcing to follow them.

**Comment by badoualy** [comment]
Yep, I'm aware of it, I often have to dig inside the Android source code when coding, but I never found any valid reason to respect this one, so, I'll just follow what I like the best :smile:

**Comment by IonutNegru87** [comment]
Hello,

Sorry for the "m" prefix. It got in my reflex to use it :)

**Comment by badoualy** [comment]
No problem, you did an awesome job with this merge request :smile: 
I'm currently merging

**Comment by badoualy** [comment]
There's an issue with your showStepTextNumber behavior, not sure how you wanted it to work,
now it's displaying the step count in the circle for **next** steps, but when we come back from a step, it'll display this instead of the circle indicator, it's not consistent

What was the intended behavior?

**Comment by badoualy** [comment]
I pushed in master for more convenience, but this feature is not working properly

**Comment by badoualy** [comment]
I did a fix, fixing my feature, but pretty sure it broke yours, I'm not sure what was your intended behavior on this

**Comment by IonutNegru87** [comment]
Hello,

That is what i intended to do, because otherwise you don't see the text number for current step.
you can enable bottom indicator to have current step indicator and text number at same time. 

I can have a look at it next week if you want to show current step bullet and text number.

**Comment by badoualy** [comment]
Test it with and without number indicator, and you'll see that something is not consistent when going back to previous step :)

**Pull request merged**
