### PR TITLE
Label support

### PR DESCRIPTION
**Pull request by rakshakhegde**
New features are:
- Label Support
- Change Label Size
- Change Label's Margin Top
- Choose label color
- Wrap long label text
- Can also take on ViewPager's titles

### CODE REVIEW

**Comment by aliusa** [comment]
I tried to do labels at #21. What if label is long? Does it wrap and doesn't go off screen?

**Comment by rakshakhegde** [comment]
**Fixed**
With this implementation, long labels **do** go offscreen. But there's plenty of space for single word or small two word phrases. Do let me know if you know of an easy technique or lib to wrap text on `Canvas`.

**Comment by rakshakhegde** [comment]
Just found [`StaticLayout`](https://developer.android.com/reference/android/text/StaticLayout.html). Will implement that ASAP. And I also included color support for labels. Will push that first.

**Comment by rakshakhegde** [comment]
Now the library will automatically pick `android:textColorSecondary` if `stpi_labelColor` is not specified. So the text will look good in dark theme too :)

**Comment by rakshakhegde** [comment]
Hey, just pushed Label Wrapping feature. Obviously it is highly exaggerated labelSize to show what really happens.



Also I've made sure there is a small gap (`2dp + 2dp => 4dp`) between the labels, so that they're not butted up against each other.

**Comment by rakshakhegde** [comment]
@badoualy Also wanted to let you know, this update always worked well with BottomIndicator feature too. This is how it looks.



Clearly there is an issue with the centre green circle in each indicator not being drawn properly. This issue persisted all along as mentioned in #18 . Will look into fixing that too. Please review my PR until then.

**Comment by badoualy** [comment]
Awesome work man!

**Comment by rakshakhegde** [comment]
Thanks! 😄

**Pull request merged**
